env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'
