language: node_js

node_js:
  - stable

notifications:
  email: false

install:
  - npm install

script:
  - webpack --config webpack.prod.js

deploy:
  local-dir: public
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
